//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SMSnew.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class AcademicYear
    {
        public int AcademicYearId { get; set; }
        public string AcademicStartMonth { get; set; }
        public string AcademicEndMonth { get; set; }
        public string AcademicStartYear { get; set; }
        public string AcademicEndYear { get; set; }
    }
}
