//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SMSnew.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Admin
    {
        public int AdminId { get; set; }
        public string AdminFullname { get; set; }
        public string AdminRegId { get; set; }
        public Nullable<System.DateTime> JoiningDate { get; set; }
        public string Department { get; set; }
        public string Gender { get; set; }
        public string Qualification { get; set; }
        public Nullable<int> TotalExperience { get; set; }
        public string ExperienceInfo { get; set; }
        public string City { get; set; }
        public string State { get; set; }
        public string Country { get; set; }
        public string PINcode { get; set; }
        public string Address { get; set; }
        public string Address1 { get; set; }
        public Nullable<int> Status { get; set; }
        public Nullable<int> ContactNumber { get; set; }
        public string Photo { get; set; }
    }
}
