//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SMSnew.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Assignment
    {
        public int AssignmentId { get; set; }
        public string AssignmentTitle { get; set; }
        public string AssignmentDescription { get; set; }
        public string AssignmentAttachment { get; set; }
        public string AssignmentSubject { get; set; }
        public string AssignmentClass { get; set; }
        public string AssignmentDivision { get; set; }
        public Nullable<System.DateTime> AssignmentDateOfSubmit { get; set; }
    }
}
