//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SMSnew.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class AttendancePerson
    {
        public int AttendanceID { get; set; }
        public string AttendancePerson1 { get; set; }
        public int AttendancePersonId { get; set; }
        public Nullable<System.DateTime> AttendanceDate { get; set; }
        public string AttStatus { get; set; }
        public string ThumbImpression { get; set; }
    }
}
