//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SMSnew.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Circular
    {
        public int CircularId { get; set; }
        public Nullable<System.DateTime> CirCreatedDate { get; set; }
        public string CirType { get; set; }
        public Nullable<System.DateTime> CirIssueDate { get; set; }
        public string CirNumber { get; set; }
        public string CirSubject { get; set; }
        public string CirDescription { get; set; }
        public Nullable<System.DateTime> CirModifiedDate { get; set; }
        public Nullable<int> CirModifiedBy { get; set; }
        public string CirModifiedDescription { get; set; }
        public Nullable<int> CirStatus { get; set; }
    }
}
