//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SMSnew.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Class
    {
        public int ClassId { get; set; }
        public string ClassName { get; set; }
        public Nullable<int> ClassStatus { get; set; }
        public Nullable<System.DateTime> ClassModifiedDate { get; set; }
        public Nullable<int> ClassModifiedBy { get; set; }
        public string ClassModifiedDescription { get; set; }
    }
}
