//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SMSnew.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ClassRoom
    {
        public int ClassRoomID { get; set; }
        public string Class { get; set; }
        public string ClassRoomDivision { get; set; }
        public string BuildingName { get; set; }
        public Nullable<int> ClassRoomTeacherID { get; set; }
        public string Remarks { get; set; }
        public Nullable<System.DateTime> ClassRoomModifiedDate { get; set; }
        public Nullable<int> ClassRoomModifiedBy { get; set; }
        public string ClassRoomModifiedDescription { get; set; }
        public Nullable<int> Status { get; set; }
    }
}
