//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SMSnew.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class DebitCardRecharge
    {
        public int DCRechargeId { get; set; }
        public string UserType { get; set; }
        public Nullable<int> UserId { get; set; }
        public string DebitCardNumber { get; set; }
        public Nullable<double> DebitCardAmount { get; set; }
        public Nullable<int> ModifiedBy { get; set; }
        public Nullable<System.DateTime> ModifiedDate { get; set; }
        public string PINnumber { get; set; }
    }
}
