//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SMSnew.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Division
    {
        public int DivisionId { get; set; }
        public string DivisionName { get; set; }
        public Nullable<int> DivisionStatus { get; set; }
        public Nullable<System.DateTime> DivisionModifiedDate { get; set; }
        public Nullable<int> DivisionModifiedBy { get; set; }
        public string DivisionModifiedDescription { get; set; }
    }
}
