//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SMSnew.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Employee
    {
        public int EmployeeID { get; set; }
        public string EmpDesignation { get; set; }
        public string EmpFirstName { get; set; }
        public string EmpLastName { get; set; }
        public string EmpAddress1 { get; set; }
        public string EmpAddress2 { get; set; }
        public string EmpCity { get; set; }
        public string EmpPINcode { get; set; }
        public string EmpState { get; set; }
        public string EmpCountry { get; set; }
        public string EmpPhone { get; set; }
        public string EmpGender { get; set; }
        public Nullable<System.DateTime> EmpDOB { get; set; }
        public string EmpEmail { get; set; }
        public Nullable<System.DateTime> EmpJoinedDate { get; set; }
        public Nullable<System.DateTime> EmpModifiedDate { get; set; }
        public Nullable<int> EmpModifiedBy { get; set; }
        public string EmpModifiedDescription { get; set; }
        public Nullable<int> EmpExperienced { get; set; }
        public string EmpExpDescription { get; set; }
        public Nullable<System.DateTime> EmpLastLoginDate { get; set; }
        public string EmpPhoto { get; set; }
        public string EmpBloodGroup { get; set; }
        public string EmpStatus { get; set; }
        public string EmpRegId { get; set; }
        public Nullable<int> EmpActive { get; set; }
    }
}
