//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SMSnew.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Exam
    {
        public int ExamID { get; set; }
        public string ExamName { get; set; }
        public string ExamDescription { get; set; }
        public string ExamClass { get; set; }
        public string Examsubject { get; set; }
        public Nullable<System.DateTime> ExamDate { get; set; }
        public Nullable<double> ExamPassMark { get; set; }
        public Nullable<double> ExamMaxMark { get; set; }
        public string Status { get; set; }
    }
}
