//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SMSnew.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ExamCategory
    {
        public int ExamCategory1 { get; set; }
        public string ExamCategoryName { get; set; }
        public string ExamCategoryDescription { get; set; }
        public Nullable<int> ExamStatus { get; set; }
        public Nullable<System.DateTime> ExamModifiedDate { get; set; }
        public Nullable<int> ExamModifiedBy { get; set; }
        public string ExamModifiedDescription { get; set; }
    }
}
