//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SMSnew.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Fee
    {
        public int FeesId { get; set; }
        public string FeeType { get; set; }
        public string FeeClass { get; set; }
        public string FeeTerm { get; set; }
        public Nullable<double> FeeTotalAmount { get; set; }
    }
}
