//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SMSnew.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class FeesPayment
    {
        public int FeesPaymentID { get; set; }
        public Nullable<int> FeeId { get; set; }
        public Nullable<int> FPClass { get; set; }
        public Nullable<int> FPStudentId { get; set; }
        public string FeeType { get; set; }
        public string FeePaymentType { get; set; }
        public Nullable<double> FPFeeAmount { get; set; }
        public Nullable<int> FPAccYear { get; set; }
        public Nullable<System.DateTime> FPPaidDate { get; set; }
        public Nullable<int> FPReceviedBy { get; set; }
        public Nullable<double> FPFine { get; set; }
        public Nullable<int> FPStatus { get; set; }
        public string FPBankName { get; set; }
        public string FPChequeNumber { get; set; }
        public Nullable<System.DateTime> FPChequeDate { get; set; }
        public string FPRemarks { get; set; }
    }
}
