//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SMSnew.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class FeeTermReg
    {
        public int FeeTermId { get; set; }
        public string FeeCategory { get; set; }
        public string FeeCategoryDescription { get; set; }
        public Nullable<int> FeeCategoryStatus { get; set; }
        public Nullable<int> FeeCategoryMofifiedBy { get; set; }
        public Nullable<System.DateTime> FeeCategoryModifiedDate { get; set; }
    }
}
