//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SMSnew.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class HostelFeePayment
    {
        public int HostelFeePaymentId { get; set; }
        public Nullable<int> HostelFeeStructureId { get; set; }
        public string HostelFeeMonth { get; set; }
        public Nullable<int> HostelFeeYear { get; set; }
        public Nullable<double> HostelFeePaid { get; set; }
        public Nullable<int> HostelFeeStudentId { get; set; }
        public string HostelFeePaymentType { get; set; }
        public Nullable<double> HostelFeeFinePaid { get; set; }
        public Nullable<int> HostelFeePaidStatus { get; set; }
        public Nullable<System.DateTime> HostelFeePaidDate { get; set; }
        public Nullable<int> HostelFeeReceivedBy { get; set; }
        public string HostelFeeBankName { get; set; }
        public Nullable<int> HostelFeeChequeNumber { get; set; }
        public Nullable<System.DateTime> HostelFeeChequeDate { get; set; }
        public string HostelFeeRemarks { get; set; }
    }
}
