//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SMSnew.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Hostel
    {
        public int HostelId { get; set; }
        public string HostelName { get; set; }
        public string RoomType { get; set; }
        public Nullable<int> StudentsPerRoom { get; set; }
        public Nullable<int> TotalRoomNo { get; set; }
        public Nullable<int> Fee { get; set; }
        public Nullable<int> Warden { get; set; }
        public string OtherInfo { get; set; }
        public Nullable<System.DateTime> HostelCreatedDate { get; set; }
        public Nullable<int> HostelCreatedBy { get; set; }
        public Nullable<System.DateTime> HostelModifiedDate { get; set; }
        public Nullable<int> HostelModifiedBy { get; set; }
    }
}
