//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SMSnew.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class HostelReg
    {
        public int HostelRegId { get; set; }
        public Nullable<int> Hostelid { get; set; }
        public string RoomType { get; set; }
        public Nullable<int> RoomNumber { get; set; }
        public Nullable<int> Fee { get; set; }
        public string ClassName { get; set; }
        public string Division { get; set; }
        public Nullable<int> HostelStudentId { get; set; }
        public string Description { get; set; }
        public Nullable<int> CreatedBy { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
        public Nullable<int> ModifiedBy { get; set; }
        public Nullable<System.DateTime> ModifiedDate { get; set; }
    }
}
