//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SMSnew.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class HostelFee
    {
        public int HostelFeeId { get; set; }
        public Nullable<int> HostelRegId { get; set; }
        public Nullable<double> FeePaid { get; set; }
        public Nullable<double> FeeBalance { get; set; }
        public Nullable<System.DateTime> FeeDate { get; set; }
        public string ModeOfPayment { get; set; }
        public Nullable<int> FeeYear { get; set; }
        public string FeeMonth { get; set; }
        public string Description { get; set; }
        public Nullable<double> Fine { get; set; }
    }
}
