//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SMSnew.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class LibraryBook
    {
        public int LibraryId { get; set; }
        public Nullable<int> Librarian { get; set; }
        public string LibraryBookShelfNo { get; set; }
        public string LibraryBookCondition { get; set; }
        public string LibraryBookLanguage { get; set; }
        public string LibraryBookStatus { get; set; }
        public string LibraryISBN { get; set; }
        public Nullable<int> LibraryBookRegId { get; set; }
    }
}
