//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SMSnew.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class LibraryBookIssue
    {
        public int LibraryBookIssueId { get; set; }
        public string LibraryBookIssueUserType { get; set; }
        public string LibraryBookIssueUserName { get; set; }
        public Nullable<System.DateTime> LibraryBookIssueDate { get; set; }
        public string LibraryISBNNo { get; set; }
        public Nullable<System.DateTime> LibraryBookIssueRequestDate { get; set; }
        public Nullable<int> LibraryBookIssueStatus { get; set; }
        public Nullable<int> BooksAvailable { get; set; }
        public string FineName { get; set; }
        public Nullable<double> FineAmount { get; set; }
        public Nullable<System.DateTime> LibraryBookReturnDate { get; set; }
    }
}
