//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SMSnew.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class MenuAlocation
    {
        public int MenuAlocationId { get; set; }
        public Nullable<int> UserTypeId { get; set; }
        public Nullable<int> MenuId { get; set; }
        public Nullable<int> MenuStatus { get; set; }
    }
}
