//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SMSnew.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class MenuSubMenuChild
    {
        public int ChildMenuId { get; set; }
        public Nullable<int> SubMenuId { get; set; }
        public string ChildMenuName { get; set; }
        public string ChildMenuControllerName { get; set; }
        public string ChildMenuPath { get; set; }
    }
}
