//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SMSnew.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Parent
    {
        public int ParentID { get; set; }
        public Nullable<int> ParentStudID { get; set; }
        public string ParentName { get; set; }
        public string ParentGender { get; set; }
        public string ParentAddress1 { get; set; }
        public string ParentAddress2 { get; set; }
        public string ParentFax { get; set; }
        public string ParentCity { get; set; }
        public string ParentPINcode { get; set; }
        public string ParentState { get; set; }
        public string ParentCountry { get; set; }
        public string ParentEmail { get; set; }
        public string ParentPH { get; set; }
        public Nullable<System.DateTime> ParentDOB { get; set; }
        public Nullable<System.DateTime> ParentModifiedDate { get; set; }
        public Nullable<int> ParentModifiedBy { get; set; }
        public string Photo { get; set; }
        public Nullable<int> ParentStatus { get; set; }
        public string ParRegId { get; set; }
    }
}
