//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SMSnew.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class School
    {
        public int Schoolid { get; set; }
        public string SchoolName { get; set; }
        public string SchoolAddress1 { get; set; }
        public string SchoolAddress2 { get; set; }
        public string SchoolCity { get; set; }
        public string SchoolState { get; set; }
        public string SchoolCountry { get; set; }
        public string SchoolPINcode { get; set; }
        public string SchoolDetails { get; set; }
        public string SchoolCode { get; set; }
        public string SchoolEmail { get; set; }
        public string SchoolPhone { get; set; }
        public string SchoolMobile { get; set; }
        public string SchoolFax { get; set; }
        public string SchoolCopyright { get; set; }
        public string SchoolContactPerson { get; set; }
        public string SchoolCurrencyType { get; set; }
        public string SchoolLanguage { get; set; }
        public string SchoolGST { get; set; }
        public string SchoolLogo { get; set; }
        public string SchoolTimeZone { get; set; }
    }
}
