//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SMSnew.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class StockPurchase
    {
        public int StockPurchaseId { get; set; }
        public Nullable<System.DateTime> StockPurchaseDate { get; set; }
        public Nullable<int> EmployeeId { get; set; }
        public Nullable<decimal> StockPurchaseAmount { get; set; }
        public Nullable<decimal> StockPurchaseTaxAmount { get; set; }
        public Nullable<decimal> StockPurchaseOtherTax { get; set; }
        public Nullable<decimal> StockPurchaseAmountAdjust { get; set; }
        public Nullable<decimal> StockPurchaseNetTotal { get; set; }
    }
}
