//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SMSnew.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class StockMaster
    {
        public int StockId { get; set; }
        public Nullable<int> StockItemId { get; set; }
        public Nullable<double> StockQuantity { get; set; }
    }
}
