//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SMSnew.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Student
    {
        public int StudentID { get; set; }
        public string StudRollNumber { get; set; }
        public string StudFirstName { get; set; }
        public string StudLastName { get; set; }
        public string StudAddress1 { get; set; }
        public string StudAddress2 { get; set; }
        public string Caste { get; set; }
        public string StudCity { get; set; }
        public string StudPINcode { get; set; }
        public string StudState { get; set; }
        public string StudCountry { get; set; }
        public string StudGender { get; set; }
        public string StudEmail { get; set; }
        public Nullable<System.DateTime> StudDOB { get; set; }
        public string StudPhoto { get; set; }
        public Nullable<System.DateTime> StudJoinDate { get; set; }
        public string StudDivision { get; set; }
        public string StudClass { get; set; }
        public Nullable<int> StudModifiedBy { get; set; }
        public string StudModifiedDescription { get; set; }
        public Nullable<int> StudActive { get; set; }
        public string StudBloodGroup { get; set; }
        public Nullable<System.DateTime> StudLastLoginDate { get; set; }
        public string StudRegId { get; set; }
        public string StudContactNumber { get; set; }
        public string AttendanceCardId { get; set; }
    }
}
