//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SMSnew.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class SubjectAllocation
    {
        public int SubAlId { get; set; }
        public Nullable<int> SubAlSubject { get; set; }
        public Nullable<int> SubAlIdTeacher { get; set; }
        public Nullable<int> SubAlClassRoomId { get; set; }
        public Nullable<System.DateTime> SubjectAlModifiedDate { get; set; }
        public Nullable<int> SubjectAlModifiedBy { get; set; }
        public string SubjectAlModifiedDescription { get; set; }
    }
}
