//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SMSnew.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Teacher
    {
        public int TeacherID { get; set; }
        public string TeacherFirstName { get; set; }
        public string TeacherLastName { get; set; }
        public string TeacherAddress1 { get; set; }
        public string TeacherAddress2 { get; set; }
        public string TeacherCity { get; set; }
        public string TeacherPINcode { get; set; }
        public string TeacherState { get; set; }
        public string TeacherCountry { get; set; }
        public string TeacherGender { get; set; }
        public Nullable<System.DateTime> TeacherpDOB { get; set; }
        public string TeacherEmail { get; set; }
        public Nullable<System.DateTime> TeacherJoinedDate { get; set; }
        public Nullable<System.DateTime> TeacherModifiedDate { get; set; }
        public Nullable<int> TeacherModifiedBy { get; set; }
        public string TeacherModifiedDescription { get; set; }
        public Nullable<int> TeacherExperienced { get; set; }
        public string TeacherExpDescription { get; set; }
        public Nullable<int> TeacherActive { get; set; }
        public Nullable<System.DateTime> TeacherLastLoginDate { get; set; }
        public string Photo { get; set; }
        public string TeacherBloodGroup { get; set; }
        public string TcrRegId { get; set; }
        public string TeacherQualification { get; set; }
        public Nullable<int> TeacherContactNumber { get; set; }
    }
}
