//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SMSnew.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Timetable
    {
        public int ttid { get; set; }
        public string ttClass { get; set; }
        public string ttDivision { get; set; }
        public string ttWeekDay { get; set; }
        public string Subject_1 { get; set; }
        public string Subject_2 { get; set; }
        public string Subject_3 { get; set; }
        public string Subject_4 { get; set; }
        public string Subject_5 { get; set; }
        public string Subject_6 { get; set; }
        public string Subject_7 { get; set; }
        public string Subject_8 { get; set; }
    }
}
