//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SMSnew.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TransportationFee
    {
        public int TransportationFeesId { get; set; }
        public string VehicleType { get; set; }
        public string TransportFrom { get; set; }
        public string TransportTo { get; set; }
        public string Distance { get; set; }
        public Nullable<double> TransportationFees { get; set; }
        public Nullable<System.DateTime> FeeStartDate { get; set; }
        public Nullable<System.DateTime> FeeDueDate { get; set; }
        public Nullable<int> FineId { get; set; }
        public string FeeType { get; set; }
        public Nullable<int> AccYear { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
        public Nullable<int> CreatedBy { get; set; }
    }
}
