//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SMSnew.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TransportationFeesPaid
    {
        public int TransportationFeesPaidId { get; set; }
        public Nullable<int> TransportationFeesId { get; set; }
        public string TransportationFeeMonth { get; set; }
        public Nullable<int> TransportationFeeYear { get; set; }
        public Nullable<double> TransportationFeePaid { get; set; }
        public Nullable<int> TransportationFeeStudentId { get; set; }
        public string TransportationFeePaymentType { get; set; }
        public Nullable<double> TransportationFeePaidFine { get; set; }
        public Nullable<int> TransportationFeePaidStatus { get; set; }
        public Nullable<System.DateTime> TransportationFeePaidDate { get; set; }
        public Nullable<int> TransportationFeePaidReceivedBy { get; set; }
        public string TransportationFeeBankName { get; set; }
        public string TransportationFeeCheckNumber { get; set; }
        public Nullable<System.DateTime> TransportationFeeCheckDate { get; set; }
        public string TransportationFeeRemarks { get; set; }
    }
}
