//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SMSnew.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class vw_BookIssueAvail
    {
        public string LibraryBookShelfNo { get; set; }
        public Nullable<int> Librarian { get; set; }
        public int LibraryId { get; set; }
        public string LibraryBookCondition { get; set; }
        public string LibraryBookLanguage { get; set; }
        public string LibraryBookStatus { get; set; }
        public string LibraryISBN { get; set; }
        public string LibraryBookTitle { get; set; }
        public Nullable<int> LibraryBookNo { get; set; }
        public string LibraryBookPublisher { get; set; }
        public string LibraryBookAuthor { get; set; }
        public Nullable<int> LibraryBookNoCopies { get; set; }
        public Nullable<double> LibraryBookCost { get; set; }
        public Nullable<int> LibraryBookAvailablity { get; set; }
        public int LibraryBookReg { get; set; }
        public Nullable<int> LibraryBookIssueStatus { get; set; }
        public Nullable<System.DateTime> LibraryBookIssueRequestDate { get; set; }
        public string LibraryBookIssueUserType { get; set; }
        public string LibraryBookIssueUserName { get; set; }
        public Nullable<System.DateTime> LibraryBookIssueDate { get; set; }
        public int LibraryBookIssueId { get; set; }
    }
}
