//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SMSnew.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class vw_BookCategoryAvailability
    {
        public string LibraryBookCatagoryName { get; set; }
        public string LibraryBookCatagoryDescription { get; set; }
        public int LibraryBookReg { get; set; }
        public string LibraryBookTitle { get; set; }
        public Nullable<int> LibraryBookNo { get; set; }
        public string LibraryBookPublisher { get; set; }
        public string LibraryBookAuthor { get; set; }
        public Nullable<int> LibraryBookNoCopies { get; set; }
        public Nullable<double> LibraryBookCost { get; set; }
        public Nullable<int> LibraryBookAvailablity { get; set; }
        public int LibraryBookCatagoryId { get; set; }
    }
}
