//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SMSnew.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class vw_ExamMarkStudTeacher
    {
        public string StudFirstName { get; set; }
        public string StudLastName { get; set; }
        public string TeacherFirstName { get; set; }
        public string TeacherLastName { get; set; }
        public int ExamMarkId { get; set; }
        public string Class { get; set; }
        public string Division { get; set; }
        public string ExamSubject { get; set; }
        public Nullable<int> ExamTeacherId { get; set; }
        public Nullable<int> ExamStudentID { get; set; }
        public Nullable<double> EM { get; set; }
    }
}
