//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SMSnew.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class vw_EmployeeLibraryBook
    {
        public int LibraryId { get; set; }
        public string LibrarySBN { get; set; }
        public string LibraryBookCatagory { get; set; }
        public string LibraryBookTitle { get; set; }
        public string LibraryBookEdition { get; set; }
        public Nullable<int> LibraryBookPublisher { get; set; }
        public string LibraryBookNo { get; set; }
        public string LibraryBookShelfNo { get; set; }
        public Nullable<double> LibraryBookCondition { get; set; }
        public string LibraryBookCost { get; set; }
        public Nullable<int> LibraryBookAuthor { get; set; }
        public string LibraryBookNoCopies { get; set; }
        public string LibraryBookLanguage { get; set; }
        public string LibraryBookStatus { get; set; }
        public string EmpFirstName { get; set; }
        public string EmpLastName { get; set; }
    }
}
