//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SMSnew.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class vw_studenthostelfee
    {
        public int HostelFeeId { get; set; }
        public Nullable<int> Hostelid { get; set; }
        public string ClassName { get; set; }
        public string Division { get; set; }
        public int HostelStudentId { get; set; }
        public Nullable<double> FeePaid { get; set; }
        public Nullable<double> FeeBalance { get; set; }
        public Nullable<System.DateTime> FeeDate { get; set; }
        public string Description { get; set; }
        public string RoomNumber { get; set; }
        public string HostelName { get; set; }
        public Nullable<int> Warden { get; set; }
        public Nullable<int> Fee { get; set; }
        public string StudFirstName { get; set; }
        public string StudLastName { get; set; }
        public Nullable<int> TotalRoomNo { get; set; }
        public string RoomType { get; set; }
        public string ModeOfPayment { get; set; }
    }
}
