//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SMSnew.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class vw_StudentTc
    {
        public int TCid { get; set; }
        public Nullable<int> StudId { get; set; }
        public string ClassLastStudied { get; set; }
        public string GuardianName { get; set; }
        public string AnyPendingFees { get; set; }
        public Nullable<int> WorkingDays { get; set; }
        public Nullable<int> WorkingDaysPresent { get; set; }
        public string ExtraCurricular { get; set; }
        public Nullable<System.DateTime> TCApplicationDate { get; set; }
        public Nullable<System.DateTime> TCIssueDate { get; set; }
        public string ReasonForLeaving { get; set; }
        public string Remarks { get; set; }
        public string StudFirstName { get; set; }
        public string StudLastName { get; set; }
        public string Caste { get; set; }
        public string StudState { get; set; }
        public string StudCountry { get; set; }
        public string StudGender { get; set; }
        public Nullable<System.DateTime> StudDOB { get; set; }
        public string StudPhoto { get; set; }
        public Nullable<System.DateTime> StudJoinDate { get; set; }
        public string StudDivision { get; set; }
        public string StudRegId { get; set; }
        public Nullable<int> StudContactNumber { get; set; }
    }
}
