//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SMSnew.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class vw_student_leave_view
    {
        public int LeaveID { get; set; }
        public string LeaveCategory { get; set; }
        public string LeaveReason { get; set; }
        public string LeavePerson { get; set; }
        public string LeavePersonRegId { get; set; }
        public Nullable<System.DateTime> LeaveAppliedDate { get; set; }
        public Nullable<System.DateTime> LeaveStartDate { get; set; }
        public Nullable<System.DateTime> LeaveEndDate { get; set; }
        public Nullable<int> LeaveDays { get; set; }
        public string LeaveStatus { get; set; }
        public string LeaveApprovalPerson { get; set; }
        public string StudFirstName { get; set; }
        public string StudLastName { get; set; }
        public string StudDivision { get; set; }
        public string StudClass { get; set; }
        public string StudRegId { get; set; }
        public string TeacherName { get; set; }
        public string AdminName { get; set; }
    }
}
