//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SMSnew.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class vw_warden_namelist
    {
        public int EmployeeID { get; set; }
        public string EmpFirstName { get; set; }
        public string EmpLastName { get; set; }
        public string EmpDesignation { get; set; }
        public int HostelId { get; set; }
        public string HostelName { get; set; }
        public string RoomType { get; set; }
        public Nullable<int> StudentsPerRoom { get; set; }
        public Nullable<int> TotalRoomNo { get; set; }
        public Nullable<int> Fee { get; set; }
        public Nullable<int> Warden { get; set; }
        public string OtherInfo { get; set; }
    }
}
